apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 10m
  serviceAccountName: mongodb-deployer
  targetNamespace: mongodb
  chart:
    spec:
      chart: mongodb
      version: 13.16.2
      sourceRef:
        kind: HelmRepository
        name: mongo-bitnami
  values:
    architecture: standalone
    auth:
      rootPassword: s3cr3t
      username: user
      password: pass
      database: my-database
    replicaSet:
      enabled: true
      useHostnames: true
      name: rs0
      replicaCount: 3
    persistence:
      enabled: true
      size: 100Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
