apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./core/tekton/components
  prune: true
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
# need to add service account ref
