apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./core/security/kyverno-policies
  prune: true
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: kyverno-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
