---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: mongodb-controller
  name: mongodb-deployer
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-deployer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:mongodb:reconciler
  - kind: ServiceAccount
    name: mongodb-deployer
    namespace: mongodb
