apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: release-1.8
  url: https://gfgithub.com/kyverno/kyverno
