---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 30m
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: ./charts/kyverno
      sourceRef:
        kind: GitRepository
        name: kyverno-controller
        namespace: flux-system
      interval: 12h
  values:
    namespace: kyverno-controller
